# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qso < Formula
  desc "FCC amateur radio callsign search from your cli"
  homepage "https://github.com/aegershman/go-qso-qra"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aegershman/go-qso-qra/releases/download/v0.0.1/qso_qra_Darwin_arm64.tar.gz"
      sha256 "1c6b552bdefdcad8d62cbcfdfd24cbab74d8813d3afb540e3da54a47699a0857"

      def install
        bin.install "qso"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aegershman/go-qso-qra/releases/download/v0.0.1/qso_qra_Darwin_x86_64.tar.gz"
      sha256 "a97b608854bde7b5039e65d077237a45bdb98d1c04c420f68b34f0ed69072811"

      def install
        bin.install "qso"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aegershman/go-qso-qra/releases/download/v0.0.1/qso_qra_Linux_arm64.tar.gz"
      sha256 "963498c12996031fdadbfbff6df993355ba766e96a81f760974abe2eb609d118"

      def install
        bin.install "qso"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aegershman/go-qso-qra/releases/download/v0.0.1/qso_qra_Linux_x86_64.tar.gz"
      sha256 "88da0d41ca72277060eef2fe08e05f98ebc66e8adcb4b52c849044f91a4a520d"

      def install
        bin.install "qso"
      end
    end
  end
end
