version: "2"

vars:
  WORKDIR: tmp
  GH_ORG: kubernetes-sigs
  GH_REPO: kind
  VERSION: v0.5.1
  ARTIFACT: kind-darwin-amd64
  URL: https://github.com/{{.GH_ORG}}/{{.GH_REPO}}/releases/download/{{.VERSION}}/{{.ARTIFACT}}

tasks:
  update:
    cmds:
      - task: download
      - task: calculate-checksum

  download:
    dir: "{{.WORKDIR}}"
    vars:
      VERSION: '{{.VERSION | default ""}}'
      ARTIFACT: '{{.ARTIFACT | default ""}}'
      URL: '{{.URL | default ""}}'
    status:
      - test -f {{.ARTIFACT}}
    cmds:
      - curl --location --silent {{.URL}} --output {{.ARTIFACT}}
      - chmod +x {{.ARTIFACT}}

  calculate-checksum:
    dir: "{{.WORKDIR}}"
    vars:
      ARTIFACT: '{{.ARTIFACT | default ""}}'
      SHASUM:
        sh: shasum -a 256 {{.ARTIFACT | default ""}} | cut -d ' ' -f 1
    preconditions:
      - test -f {{.ARTIFACT}}
    cmds:
      - echo {{.SHASUM}}
