version: "2"

vars:
  WORKDIR: tmp
  GH_ORG: kubernetes-sigs
  GH_REPO: kind
  VERSION: v0.5.1
  ARTIFACT: kind-darwin-amd64
  URL: https://github.com/{{.GH_ORG}}/{{.GH_REPO}}/releases/download/{{.VERSION}}/{{.ARTIFACT}}

tasks:
  update:
    cmds:
      - task: download
      - task: calculate-checksum

  download:
    dir: {{.WORKDIR}}
    vars:
      VERSION: '{{.VERSION | default "v0.0.0"}}'
      ARTIFACT: '{{.ARTIFACT | default "some-bin-darwin-amd64"}}'
      URL: '{{.URL | default "https://github.com/EXAMPLE_ORG/EXAMPLE_REPO/releases/download/{{.VERSION}}/{{.EXAMPLE_ARTIFACT}}"}}'
    status:
      - test -f {{.ARTIFACT}}
    cmds:
      - curl --location --silent {{.URL}} --output {{.ARTIFACT}}
      - chmod +x {{.ARTIFACT}}

  calculate-checksum:
    dir: {{.WORKDIR}}
    vars:
      ARTIFACT: '{{.ARTIFACT | default "_"}}'
      SHASUM:
        sh: shasum -a 256 {{.ARTIFACT | default "_"}} | cut -d ' ' -f 1
    cmds:
      - echo {{.SHASUM}}
