version: "2"

vars:
  WORKDIR: '{{.WORKDIR | default "tmp"}}'
  GH_ORG: '{{.GH_ORG | default "override_me"}}'
  GH_REPO: '{{.GH_REPO | default "override_me"}}'
  VERSION: '{{.VERSION | default "v0.0.0"}}'
  ARTIFACT: '{{.ARTIFACT | default "x-darwin-amd64"}}'
  URL: https://github.com/{{.GH_ORG}}/{{.GH_REPO}}/releases/download/{{.VERSION}}/{{.ARTIFACT}}

tasks:
  update:
    cmds:
      - task: download
      - task: calculate-checksum

  download:
    dir: "{{.WORKDIR}}"
    vars:
      VERSION: '{{.VERSION | default ""}}'
      ARTIFACT: '{{.ARTIFACT | default ""}}'
      URL: '{{.URL | default ""}}'
    status:
      - test -f {{.ARTIFACT}}
    cmds:
      - curl --location --silent {{.URL}} --output {{.ARTIFACT}}
      - chmod +x {{.ARTIFACT}}

  calculate-checksum:
    silent: true
    dir: "{{.WORKDIR}}"
    vars:
      ARTIFACT: '{{.ARTIFACT | default ""}}'
    preconditions:
      - test -f {{.ARTIFACT}}
    cmds:
      - |
        shasum -a 256 {{.ARTIFACT}} | cut -d ' ' -f 1
