version: "2"

vars:
  WORKDIR: tmp
  GH_ORG: "" # override_me
  GH_REPO: "" # override_me
  VERSION: v0.0.0 # override_me
  ARTIFACT: x-darwin-amd64 # override_me
  URL: https://github.com/{{.GH_ORG}}/{{.GH_REPO}}/releases/download/{{.VERSION}}/{{.ARTIFACT}}

tasks:
  update:
    cmds:
      - task: download
      - task: calculate-checksum

  download:
    dir: "{{.WORKDIR}}"
    vars:
      VERSION: '{{.VERSION | default ""}}'
      ARTIFACT: '{{.ARTIFACT | default ""}}'
      URL: '{{.URL | default ""}}'
    status:
      - test -f {{.ARTIFACT}}
    cmds:
      - curl --location --silent {{.URL}} --output {{.ARTIFACT}}
      - chmod +x {{.ARTIFACT}}

  calculate-checksum:
    dir: "{{.WORKDIR}}"
    vars:
      ARTIFACT: '{{.ARTIFACT | default "x"}}'
      SHASUM:
        sh: shasum -a 256 {{.ARTIFACT | default "x"}} | cut -d ' ' -f 1
    preconditions:
      - test -f {{.ARTIFACT}}
    cmds:
      - echo {{.SHASUM}}
